# This is a basic configuration file for Dependabot.
# It will check for updates to all dependencies in the GitHub Actions workflow files.

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
